name: Release
on:
  push:
    tags:
      - v*
jobs:
  create-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
