# This is a basic workflow to help you get started with Actions

name: Unit test

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # https://github.com/marketplace/actions/setup-clojure
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@3.1
        with:
          graalvm-version: '19.3.4.java11'
      - uses: DeLaGuardo/setup-clojure@3.1
        with:
          cli: '1.10.1.763'

      - run: clojure -M:test:headless:runner
